name = "footbridge"
compatibility_date = "2024-01-01"
pages_build_output_dir = "src"

[vars]
ENVIRONMENT = "production"
RESEND_FROM_EMAIL = "noreply@footbridge.hu"
RESEND_TO_EMAIL = "hello@footbridge.hu"
ANALYTICS_DOMAIN = "footbridge.hu"
SITE_URL = "https://footbridge.hu"

[[kv_namespaces]]
binding = "CONTENT"
id = "a76c118ae5f04024974f55447a85c256"

[[kv_namespaces]]
binding = "LEADS"
id = "48747eb263e14c54a3b740ea7d83469b"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "5d5d8af00d5547a4b5bbc528d6f4b5bb"
